---
title: "Git, GitHub, Command Line, and SQL"
toc: true
---

This page provides a comprehensive collection of resources focused on Git, GitHub, the Command Line, and SQL. On this page, you will find tutorials, books, and training materials that can get you started on the tools listed above.

## Git

### Basics and Summaries

1)  [Git Basics](https://www.theodinproject.com/lessons/foundations-git-basics)
2)  [Git Cheatsheet](https://anupamkumarkrishnan.hashnode.dev/git-cheatsheet)
3)  [Git/GitHub Cheatsheet](https://training.github.com/downloads/github-git-cheat-sheet/)
4)  [A Visual Git Reference](http://marklodato.github.io/visual-git-guide/index-en.html)
5)  [Visualizing Git Concepts with D3](http://onlywei.github.io/explain-git-with-d3/#)
6)  [Git Immersion](https://gitimmersion.com/)
7)  [Learn Git Branching](https://learngitbranching.js.org/)
8)  [Introduction to Git & Github](https://debadritaghosh.hashnode.dev/introduction-to-git-github)
9)  [How to Use Git/GitHub with R](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/)
10) [git ready](https://gitready.com/)

### Books

1)  [Pro Git Book](https://git-scm.com/book/en/v2)
2)  [Happy Git and GitHub for the user](https://happygitwithr.com/)

### Tutorials

1)  [Understanding Git Conceptually](https://www.cduan.com/technical/git/)
2)  [Become a git guru](https://www.atlassian.com/git/tutorials)
3)  [Git and RStudio](https://rpubs.com/marschmi/105639)
4)  [Good Enough Practices in Scientific Computing](https://carpentries-incubator.github.io/good-enough-practices/index.html)
5)  [Version Control (Git)](https://missing.csail.mit.edu/2020/version-control/)

### Git Troubleshooting

1)  [On undoing, fixing, or removing commits in git](https://sethrobertson.github.io/GitFixUm/fixup.html)
2)  [git pretty](http://justinhileman.info/article/git-pretty/)
3)  [Fixing Common Git Mistakes](https://maggieappleton.com/git-mistakes)

## GitHub

### Basics

1)  [Getting started with Git and GitHub: the complete beginner's guide](https://towardsdatascience.com/getting-started-with-git-and-github-6fcd0f2d4ac6)
2)  [An Intro to Git and GitHub for Beginners (Tutorial)](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
3)  [Get started with Git and GitHub](https://aosmith16.github.io/spring-r-topics/slides/week01_introduction_git_and_github.html#1)
4)  [Mastering GitHub in 4 Steps](https://frontenddoctor.hashnode.dev/mastering-github-in-4-steps)
5)  [GitHub for supporting, reusing, contributing, and failing safely](https://www.openscapes.org/blog/2022/05/27/github-illustrated-series/)

### Training and Tutorials

1)  [Introducing GitHub Global Campus](https://github.blog/2021-09-01-introducing-github-global-campus/)
2)  [Collaboration, version control and learning to commit](https://personalpages.manchester.ac.uk/staff/david.selby/rthritis/2021-03-12-git/)
3)  [Making Your First GitHub R Project](https://codehorizons.com/making-your-first-github-r-project/)

### Applications

1)  [Introduction to GitHub Actions to R users](https://beamilz.com/posts/series-gha/2022-series-gha-1-what-is/en/)
2)  [How to effortlessly create a website for free with GitHub Pages](https://towardsdatascience.com/how-to-create-a-free-github-pages-website-53743d7524e1)
3)  [Introducing Jekyll Now for GitHub-hosted blogs](https://www.jekyllnow.com/)
4)  [Software development practices](https://r-pkgs.org/software-development-practices.html)

## Command Line (Bash, UNIX, and Linux)

### Books

1)  [Command Line Basics for R Users](https://bash-intro.rsquaredacademy.com/)

### Lectures and Tutorials

1)  [Intro to UNIX](https://data-skills.github.io/unix-and-bash/)
2)  [The Unix Shell 1](https://swcarpentry.github.io/shell-novice/)
3)  [The Unix Shell 2](https://thejacksonlaboratory.github.io/introduction-to-hpc/)

## SQL

### Collection of SQL Resources

1)  [21 of the best free resources to learn SQL](https://code-love.com/2018/09/01/21-learn-sql/)

### Tutorials

1)  [PostgreSQL Tutorial](https://www.postgresqltutorial.com/)
2)  [The SQL Tutorial for Data Analysis](https://mode.com/sql-tutorial/introduction-to-sql/)
3)  [SQL Hackerrank Channels](https://www.hackerrank.com/domains/sql)
4)  [SQL Tutorial 1](https://www.w3schools.com/sql/)
5)  [SQL Tutorial 2](https://sqlzoo.net/wiki/SQL_Tutorial)
6)  [SQLBolt](https://sqlbolt.com/)
7)  [SQL queries don't start with SELECT](https://jvns.ca/blog/2019/10/03/sql-queries-don-t-start-with-select/)
8)  [A Visual Explanation of SQL Joins](https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/)
