---
title: "Quarto"
toc: true
---

The Quarto page contains a list of resources that are focused on the relatively new Quarto software. It includes various beginner guides to help one get started on their Quarto journey. Additionally, I provide links to resources for other tools such as RMarkdown and Distill.

## Introduction and Tutorials

### Curated collection of Quarto Resources

1)  [Awesome Quarto](https://github.com/mcanouil/awesome-quarto)

### Beginner's Guide

1)  [Quarto](https://quarto.org/)
2)  [Tutorial: Hello, Quarto](https://quarto.org/docs/get-started/hello/rstudio.html)
3)  [What is Quarto? RStudio rolls out next-generation R Markdown](https://www.infoworld.com/article/3666743/what-is-quarto-rstudio-quietly-rolls-out-next-generation-r-markdown.html)
4)  [We don't talk about Quarto](https://www.apreshill.com/blog/2022-04-we-dont-talk-about-quarto/)
5)  [Build a simple website with R and Quarto in under 10 minutes](https://philipp.quarto.pub/my-first-website/article.html)
6)  [Getting Started with Quarto](https://rstudio-conf-2022.github.io/get-started-quarto/)
7)  [The ultimate guide to starting a Quarto blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html)
8)  [Creating a blog with Quarto in 10 steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/)
9)  [Making Slides in Quarto with reveal.js](https://meghan.rbind.io/blog/quarto-slides/)

### R Markdown and Distill

1)  [The Distillery](https://distillery.rbind.io/showcase.html)
2)  [R Markdown for Web Pages](https://www.markdownguide.org/basic-syntax/)
3)  [Porting a distill blog to quarto](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/)
4)  [RMarkdown](https://rmarkdown.rstudio.com/index.html)
