---
title: "R and RStudio"
toc: true
---

This page provides a comprehensive collection of R/RStudio resources. On this page, you will find a list of personal websites and blogs that do some great work in R/RStudio. Additionally, there is a list of resources (books, tutorials, and blogs) focused on the basics of R/RStudio.

## Personal Websites and Blogs

1)  [Silvia Canelon](https://silviacanelon.com/blog/)
2)  [Meghan Hall](https://meghan.rbind.io/blog/)
3)  [Paul Villanueva](https://pommevilla.netlify.app/)
4)  [Shannon Pileggi](https://www.pipinghotdata.com/index.html)
5)  [Katherine (Kat) Hoffman](https://www.khstats.com/)
6)  [Deisy Gysi](https://deisygysi.github.io/)
7)  [Simon J](https://drsimonj.svbtle.com/)
8)  [Ryo Nakagawara](https://ryo-n7.github.io/)
9)  [Kieran Healy - Some Favorite Things](https://kieranhealy.org/blog/)
10) [François Husson](https://francoishusson.wordpress.com/)
11) [Rebecca Barter](https://www.rebeccabarter.com/)
12) [Alboukadel Kassambara](http://www.alboukadel.com/)
13) [Michael Toth](https://michaeltoth.me/)
14) [Sam Abbott](https://samabbott.co.uk/)
15) [Shel Kariuki](https://shelkariuki.netlify.app/)
16) [Austin Wehrwein](https://austinwehrwein.com/)
17) [Nicola Rennie](https://nrennie.rbind.io/)
18) [R for Ecology](https://www.rforecology.com/)
19) [Stats and R](https://statsandr.com/)
20) [Roland Krasser](https://rolkra.github.io/)
21) [Martin Chan - Musings on R](https://martinctc.github.io/blog/)
22) [Rsquared Academy](https://blog.rsquaredacademy.com/)
23) [Olivier Gimenez](https://oliviergimenez.github.io/)
24) [David Schoch](https://mr.schochastics.net/)

More to come...

## Basics

### Curated list of resources

1)  [Big Book of R](https://www.bigbookofr.com/)
2)  [FREE R READING MATERIAL](https://committedtotape.shinyapps.io/freeR/)
3)  [An R Community Public Library](https://rviews.rstudio.com/2021/11/04/bookdown-org/)
4)  [Awesome R Learning Resources](https://github.com/iamericfletcher/awesome-r-learning-resources)
5)  [R Cheatsheets](https://rviews.rstudio.com/2021/03/10/rstudio-open-source-resorurces/)
6)  [Posit Cheatsheets](https://posit.co/resources/cheatsheets/)
7)  [R4theRestofUs](https://rfortherestofus.com/resources/)
8)  [EDUCATORS R LEARNERS](https://educators-r-learners.netlify.app/resources/)
9)  [R and Data Mining](https://www.rdatamining.com/)

### Books

1)  [R4DataScience](https://r4ds.had.co.nz/)
2)  [R4DataScience - Solutions](https://jrnold.github.io/r4ds-exercise-solutions/)
3)  [R4DataScience, 2nd Edition](https://r4ds.hadley.nz/)
4)  [R Workflow A](https://hbiostat.org/rflow/)
5)  [R Workflow B](https://www.fharrell.com/post/rflow/)
6)  [What They Forgot to Teach You About R](https://rstats.wtf/)
7)  [R for Researchers: An Introduction](https://tysonbarrett.com/Rstats/index.html)
8)  [Supervised Machine Learning for Text Analysis in R](https://smltar.com/)
9)  [Reproducible Analytical Pipelines - Master's of Data Science](https://rap4mads.eu/)
10) [R for Data Analysis](https://trevorfrench.github.io/R-for-Data-Analysis/)
11) [Data Analysis and Prediction Algorithms with R](http://rafalab.dfci.harvard.edu/dsbook/)
12) [Hands-On Programming with R](https://jjallaire.github.io/hopr/)
13) [R for Health Data Science](https://argoshare.is.ed.ac.uk/healthyr_book/)
14) [R for Health Data Science Resources](https://healthyr.surgicalinformatics.org/resources.html#resources)
15) [Data Science in Education Using R](https://datascienceineducation.com/)
16) [A Succinct Intro to R](http://r-guide.steveharoz.com/)
17) [Data Science: A First Introduction](https://datasciencebook.ca/)
18) [The Epidemiologist R Handbook](https://epirhandbook.com/en/index.html)
19) [Introduction to R, version 2](https://monashdatafluency.github.io/r-intro-2/)
20) [Technical Foundations of Informatics](https://info201.github.io/)
21) [Data Science for Economists and Other Animals](https://grantmcdermott.com/ds4e/index.html)
22) [Efficient R programming](https://bookdown.org/csgillespie/efficientR/)
23) [An Introduction to R](https://intro2r.com/)
24) [YaRrr! The Pirate's Guide to R](https://bookdown.org/ndphillips/YaRrr/)
25) [Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/)
26) [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/)
27) [Modern Dive](https://moderndive.com/1-getting-started.html)
28) [Advanced R](https://adv-r.hadley.nz/)
29) [Yet Again: R + Data Science](https://yards.albert-rapp.de/)
30) [Public Policy Analytics](https://github.com/urbanSpatial/Public-Policy-Analytics-Landing)
31) [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/)
32) [Deep R Programming](https://deepr.gagolewski.com/)
33) [Urban Informatics](https://ui.josiahparry.com/)
34) [Mastering Spark with R](https://therinspark.com/)
35) [Modern Statistics with R](https://modernstatisticswithr.com/)
36) [R for the Rest of Us: A Statistics-Free Introduction](https://book.rfortherestofus.com/)
37) [Agile Data Science with R](https://edwinth.github.io/ADSwR/)

### R and GPT

1)  [R and gpttools](https://jameshwade.github.io/gpttools/)

### Snowflake

1)  [Analyze Data with R using Posit Workbench and Snowflake](https://quickstarts.snowflake.com/guide/analyze_data_with_r_using_posit_workbench_and_snowflake/index.html#0)
2)  [Analyze Data in R with Posit Workbench and Snowflake](https://medium.com/snowflake/analyze-data-in-r-with-posit-workbench-and-snowflake-7b837b27337b)

### Conference Workshops

1)  [Talk recordings and workshop materials from rstudio::conf(2022)](https://www.rstudio.com/blog/talks-and-workshops-from-rstudio-conf-2022/)
2)  [Links to slides from rstudio::conf 2020](https://github.com/EmilHvitfeldt/RStudioConf2020Slides)
3)  [NHS-R](https://nhsrcommunity.com/nhs-r-2020-week-long-conference-so-much-great-content-so-little-time-to-catch-it-all/)
4)  [useR! 2019 Highlights](https://ryo-n7.github.io/2019-07-21-user2019-reflections/)
5)  [ToulouseR 2019](http://www.user2019.fr/talk_schedule/)

### Package Development

1)  [R Packages](https://r-pkgs.org/index.html)
2)  [Introduction to Package Development](https://shelkariuki.netlify.app/talk/packagedevelopment/)
3)  [Your first R package in 1 hour](https://www.pipinghotdata.com/posts/2020-10-25-your-first-r-package-in-1-hour/)
4)  [Developing R packages](https://github.com/jtleek/rpackages)
5)  [Reflections on building my first few R packages](https://www.mainard.co.uk/post/reflections-on-building-my-first-few-r-packages/)
6)  [R Package Tutorial](https://github.com/loukesio/R-package-tutorial)

### Newsletters

1)  [RWeekly](https://rweekly.org/)

### Training Courses and Tutorials

1)  [RStudio Education](https://education.rstudio.com/teach/)
2)  [RStudio Education Beginners](https://education.rstudio.com/learn/beginner/)
3)  [RStudio Education Intermediates](https://education.rstudio.com/learn/intermediate/)
4)  [RStudio Education Experts](https://education.rstudio.com/learn/expert/)
5)  [Quick-R Tutorial](https://www.statmethods.net/)
6)  [Learn R in R](https://swirlstats.com/)
7)  [Learning R With Education Datasets](https://rviews.rstudio.com/2020/06/11/learning-r-with-education-datasets/)
8)  [STAT 545 Data wrangling, exploration, and analysis with R](https://stat545.com/)
9)  [STHDA](http://www.sthda.com/english/)
10) [datascienceplus](https://datascienceplus.com/)
11) [Statistical Computing in R](https://www.stephaniehicks.com/jhustatcomputing2022/schedule)
12) [Statistical Programming Paradigms and Workflows](https://www.stephaniehicks.com/jhustatprogramming2022/schedule)
13) [Teaching Statistics and Data Science Online](https://mine-cetinkaya-rundel.github.io/teach-r-online/)
14) [An Introduction to Docker for R Users](https://colinfay.me/docker-r-reproducibility/)
15) [R Bootcamp](https://r-bootcamp.netlify.app/)
16) [Kane's Data Science Course](https://bootcamp.davidkane.info/)
17) [Andrew Heiss R-based courses](https://www.andrewheiss.com/teaching/)
18) [STREAMLINING WITH R](https://meghan.rbind.io/slides/neair/neair.html#/title-slide)
19) [R Bootcamp](https://r-bootcamp.netlify.app/)
20) [Advanced R Topics](https://aosmith16.github.io/spring-r-topics/materials.html)
21) [R for Water Resources Data Science](https://www.r4wrds.com/)
22) [Reproducible science workshop](https://oliviergimenez.github.io/reproducible-science-workshop/)
23) [Think R](https://thinkr.fr/)
24) [R 4 Beginners](https://r4b-vu.netlify.app)
25) [Applied Economics with R](https://hhsievertsen.github.io/applied_econ_with_r/)
26) [Ready for R](https://ready4r.netlify.app/)
27) [Interpretable Machine Learning](https://advanced-ds-in-r.netlify.app/posts/2021-03-31-imllocal/)
28) [R basics: a practical introduction to R](https://ariel.rbind.io/workshop/rbasics/#interactive-tutorials)
29) [Introduction to R](https://github.com/kristineccles/Introduction_to_R)
30) [fasteR: Fast Lane to Learning R!](https://github.com/matloff/fasteR)
31) [Analysis of community ecology data in R](https://www.davidzeleny.net/anadat-r/doku.php/en:start)
32) [R Screencasts](https://www.rscreencasts.com/)
33) [R for better science in less time](https://openscapes.github.io/slides/betterscience/socalR#1)
34) [R and Stats](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html)
35) [Palmer Archipelago Penguins Data](https://journal.r-project.org/articles/RJ-2022-020/)
36) [We are R-Ladies](https://github.com/emitanaka/wearerladies)
37) [Web Scraping in R: A Quick Guide](https://www.scrapingdog.com/blog/web-scraping-r/)
38) [Word Clouds in R](https://spencerschien.info/post/data_viz_how_to/dense_word_clouds/)
39) [Data science tutorials](https://hausetutorials.netlify.app/)
40) [MARKET ANALYSIS COURSE](https://skranz.github.io//r/2020/06/10/MarketAnalysis.html)
41) [RTutor: Interactive R Problem Sets](http://skranz.github.io/RTutor/)
42) [Data Wrangling and dplyr](https://suzan.rbind.io/categories/tutorial/)
43) [Intro to R for Programming](https://favstats.github.io/ds3_r_intro/#1)
44) [purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html)
45) [Intro to R: Shiny App](https://hhsievertsen.shinyapps.io/r_introduction/#section-welcome)
46) [Spatial Data Science](https://spatialanalysis.github.io/tutorials/)
47) [Generalized Additive Models in R](https://noamross.github.io/gams-in-r-course/)
48) [Visualizing the Bayesian workflow in R](https://www.monicaalexander.com/posts/2020-28-02-bayes_viz/)
49) [Create machine learning models: An R version](https://rpubs.com/eR_ic/exploRe)
50) [Wrangling Unruly Data](https://www.rstudio.com/blog/wrangling-unruly-data/)
51) [Cleaning UK Office for National Statistics data in R](http://lesscrime.info/post/cleaning-ons-data/)
52) [How to Automate EDA with DataExplorer in R](https://www.programmingwithr.com/how-to-automate-eda-with-dataexplorer-in-r/)
53) [Rachael's R Tutorials](https://www.kaggle.com/code/rtatman/rachael-s-r-tutorials/notebook)
54) [Manipulating Data with dplyr](https://www.dominodatalab.com/blog/manipulating-data-with-dplyr)
55) [Get me to the church on time with R spatial](https://nacnudus.github.io/duncangarmonsway/posts/2019-04-22-get-me-to-the-church-on-time-with-r-spatial/)
56) [Multivariate data analysis with R and vegan](https://github.com/gavinsimpson/physalia-multivariate#multivariate-data-analysis-with-r-and-vegan)
57) [A Course in Exploratory Data Analysis](https://bayesball.github.io/EDA/index.html)
58) [Exploratory Data Analysis with explore package](https://rolkra.github.io/explore-130/)
59) [Getting Started with R](https://support.posit.co/hc/en-us/articles/201141096-Getting-Started-with-R)
60) [R Crash Course](https://bioinformatics-core-shared-training.github.io/r-crash-course/crash-course.nb.html)
61) [Four ways to streamline your R workflows](https://nrennie.rbind.io/blog/four-ways-streamline-r-workflows/)
62) [One billion row challenge using base R](https://blog.schochastics.net/posts/2024-01-08_one-billion-rows-challenge/)
63) [Let's talk about joins](https://cghlewis.com/blog/joins/)
64) [How to Get Good with R?](https://www.njtierney.com/post/2023/11/10/how-to-get-good-with-r/)
65) [S-Cubed Courses](https://scubed.rbind.io/courses/)

### Tools

1)  [R Universe Authors and Packages](https://r-universe.dev/search/)
2)  [R-hub](https://blog.r-hub.io/)
3)  [R in Visual Studio Code](https://code.visualstudio.com/docs/languages/r)
4)  [R Libraries Every Data Scientist Should Know](https://pyoflife.com/r-libraries-every-data-scientist-should-know/)
5)  [Packages for Exploratory Data Analysis in R](https://www.r-bloggers.com/2022/04/packages-for-exploratory-data-analysis-in-r/)
6)  [15 Essential packages in R for Data Science](https://finnstats.com/index.php/2021/04/07/essential-packages-in-r/)
7)  [WebR - R in the Browser](https://docs.r-wasm.org/webr/latest/)
8)  [Five useful R functions](https://www.neilwright.uk/posts/five-r-functions)
9)  [Six not-so-basic base R functions](https://ivelasq.rbind.io/blog/not-so-basic-base-r-functions/)
10) [Get Good with R: Typing Skills and Shortcuts](https://www.njtierney.com/post/2023/12/04/get-good-type-fast/)

### Troubleshooting / Tips and Tricks

1)  [How to Use "not in" operator in Filter](https://www.r-bloggers.com/2022/06/how-to-use-not-in-operator-in-filter/)
2)  [Common R Mistakes in Data Viz](https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html#content)
3)  [R Examples](https://www.rexamples.com/)
4)  [R Tips and Tricks](https://datacornering.com/)

### Hackathons and Competitions

1)  [Kaggle Housing Price Tutorial](https://www.kaggle.com/c/home-data-for-ml-course/overview/tutorials)

## Tidyverse

### Basics

1)  [A very short introduction to Tidyverse](https://dominicroye.github.io/en/2020/a-very-short-introduction-to-tidyverse/)
2)  [The Tidyverse in Action](https://evamaerey.github.io/tidyverse_in_action/tidyverse_in_action.html#1)
3)  [A Gentle Guide to Tidy Statistics in R](https://themockup.blog/posts/2018-12-10-a-gentle-guide-to-tidy-statistics-in-r/)
4)  [An Introduction to R through the tidyverse](https://pmacdasci.github.io/r-intro-tidyverse/)
5)  [C'est quoi, le tidyverse?](https://thinkr.fr/c-est-quoi-le-tidyverse/#Mettre_en_forme_ses_donnees_avec_la_package_tidyr)
6)  [Basic usage of tidycensus](https://walker-data.com/tidycensus/articles/basic-usage.html)

### Books

1)  [Tidyverse Skills for Data Science](https://jhudatascience.org/tidyversecourse/)
2)  [Modern R with the tidyverse](http://modern-rstats.eu/)
3)  [Text Mining with R: A Tidy Approach](https://www.tidytextmining.com/index.html)
4)  [Tidy Finance with R](https://www.tidy-finance.org/r/)

### Workshops

1)  [Tidyverse Workshop Series](https://github.com/nuitrcs/r-tidyverse)

### Tips and Tricks

1)  [Eight R Tidyverse tips for everyday data engineering](https://tomaztsql.wordpress.com/2022/07/14/eight-r-tidyverse-tips-for-everyday-data-engineering/)
2)  [Tidyverse Tips](https://oliviergimenez.github.io/tidyverse-tips/)

### Tutorials

1)  [Data Science LADAL Tutorials](https://ladal.edu.au/tutorials.html)
2)  [Pivoting data from columns to rows (and back!) in the tidyverse](https://www.storybench.org/pivoting-data-from-columns-to-rows-and-back-in-the-tidyverse/)
3)  [Reshaping data frames using pivot functions from {tidyr} and tally from {dplyr}](https://tidytuesday.netlify.app/posts/2022-07-05-sf-rents/)
4)  [Finding the modal school district](https://ivelasq.rbind.io/blog/modal-district/)
5)  [Teaching the tidyverse in 2021](https://www.tidyverse.org/blog/2021/08/teach-tidyverse-2021/#new-teaching-and-learning-resources)
6)  [Data manipulation with the tidyverse](https://evamaerey.github.io/data_manipulation/about)
7)  [The TidyVerse in Action](https://evamaerey.github.io/tidyverse_in_action/tidyverse_in_action.html#1)
8)  [Transitioning into the tidyverse (part 1)](https://www.rebeccabarter.com/blog/2019-08-05_base_r_to_tidyverse/)
9)  [Transitioning into the tidyverse (part 2)](https://www.rebeccabarter.com/blog/2019-08-05_base_r_to_tidyverse_pt2/)
10) [Introduction to using Databases in R, with Tidyverse tools](https://sciencificity.github.io/saf-workshop-r-and-sql/#1)
11) [Wrangling penguins: some basic data wrangling in R with dplyr](https://allisonhorst.shinyapps.io/dplyr-learnr/#section-welcome)
12) [Visualize {dplyr}](https://www.andrewheiss.com/blog/2024/04/04/group_by-summarize-ungroup-animations/)
13) [Visualize the Tidyverse](https://www.garrickadenbuie.com/project/tidyexplain/)
14) [Tidy Intelligence](https://www.tidy-intelligence.com/)

## Tidymodels in R

### Basics

1)  [A Gentle Introduction to tidymodels](https://rviews.rstudio.com/2019/06/19/a-gentle-intro-to-tidymodels/)
2)  [Tidymodels](https://www.tidymodels.org/)
3)  [The Case for tidymodels](https://rviews.rstudio.com/2020/04/21/the-case-for-tidymodels/)
4)  [Caret vs. tidymodels - comparing the old and new](https://konradsemsch.netlify.app/2019/08/caret-vs-tidymodels-comparing-the-old-and-new/)
5)  [Tidymodels: tidy machine learning in R](https://www.rebeccabarter.com/blog/2020-03-25_machine_learning/)

### Books

1)  [Tidy Modeling with R](https://www.tmwr.org/)
2)  [ISLR tidymodels labs](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/)
3)  [Modeling Data in the Tidyverse](https://jhudatascience.org/tidyversecourse/model.html#the-tidymodels-ecosystem-1)
4)  [Feature Engineering](https://bookdown.org/max/FES/intro-intro.html#)
5)  [Forecasting: Principles and Practice](https://otexts.com/fpp3/)

### Conferences

1)  [Introduction to Machine Learning with the Tidyverse](https://education.rstudio.com/blog/2020/02/conf20-intro-ml/)
2)  [RStudio Conf Workshop Materials](https://conf20-intro-ml.netlify.app/materials/)
3)  [Tidymodels package for survival models](https://hfrick.github.io/rstudio-conf-2022/#/section)

### Tutorials

1)  [Sample Story: When Will NYC's Subway Ridership Recover?](https://jlaw.netlify.app/2022/08/29/when-will-nyc-s-subway-ridership-recover/)
2)  [#TidyTuesday and tidymodels](https://juliasilge.com/blog/intro-tidymodels/)
3)  [tidypredict](https://tidypredict.tidymodels.org/)
4)  [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering/)
5)  [Experimenting with machine learning in R with tidymodels and the Kaggle titanic dataset](https://oliviergimenez.github.io/learning-machine-learning/)
