---
title: "Data Journalism Tools and Stories"
toc: true
---

This page provides a comprehensive collection of resources focused on data journalism tools and resources. On this page, you will find a list of personal websites and blogs that do some great work in data journalism. Additionally, there is a list of good examples of data stories to emulate.

## Data Journalism

### Blogs and Websites

A listing of data journalism practitioners and companies to follow:

1)  [Seth Stephens-Davidowitz](http://sethsd.com/research/)
2)  [Quant Editing](https://www.laurabronner.com/quant-editing)
3)  [Amber Thomas](https://pudding.cool/author/amber-thomas/)
4)  [Data Journalism and Viz Accounts](https://www.interhacktives.com/2019/10/28/14-data-journalism-and-data-visualisation-instagram-accounts-to-follow/)
5)  [Flowing Data Website](https://flowingdata.com/)

### Guides

1)  [GitHub Data Journalism](https://github.com/search?q=data+journalism)
2)  [A Beginner's Guide to Data Journalism: Let's Build a Story From Scratch](https://www.freecodecamp.org/news/data-journalism-isnt-for-the-select-let-s-work-out-a-story-together-from-scratch-dd85b3017f4a/)
3)  [Quick Guide to Data Journalism](https://www.datacamp.com/blog/quick-guide-to-data-journalism)
4)  [Data journalism: a guide for editors](https://datajournalism.com/read/longreads/data-journalism-a-guide-for-editors)
5)  [Developing Data Journalists in the Developing World](https://source.opennews.org/articles/developing-data-journalists-developing-world)

### Writing

1)  [Interrogating Data: A Science Writer's Guide to Data Journalism](https://www.theopennotebook.com/2020/07/28/interrogating-data-a-science-writers-guide-to-data-journalism/)
2)  [The Beginning, The Middle, & The New Beginning](https://old.duncangeere.com/newbeginning/)
3)  [How data journalists create beautiful feature stories](https://shorthand.com/the-craft/how-data-journalists-create-beautiful-feature-stories/index.html)
4)  [A data journalist's guide to building a hypothesis](https://datajournalism.com/read/longreads/hypothesis-data-journalism)
5)  [Flowing Data Story Formats](https://flowingdata.com/2019/06/17/story-formats-for-data/)
6)  [Telling Stories With Data: A Simple Math Guide](https://medium.datadriveninvestor.com/journalism-in-the-data-driven-world-a-simple-math-guide-32d106fc3041)
7)  [Data Biographies: Getting to Know Your Data](https://gijn.org/2017/03/27/data-biographies-getting-to-know-your-data/)
8)  [Putting data back into context](https://datajournalism.com/read/longreads/putting-data-back-into-context)
9)  [Dueling Data](http://duelingdata.blogspot.com/)

### Tools

1)  [Data Journalism Tools](https://www.muckrock.com/)
2)  [Data Journalism and Visualization with Free Tools](https://journalismcourses.org/course/dataviz/)
3)  [Storytelling Tools](https://shorthand.com/the-craft/visual-storytelling-tools/index.html)
4)  [StoryBench: The future of machine learning in journalism](https://www.storybench.org/the-future-of-machine-learning-in-journalism/)
5)  [How ProPublica Analyzed Pardon Data](https://www.propublica.org/article/how-propublica-analyzed-pardon-data)

### Tutorials

1)  [Mapping search data from Google Trends in R](https://www.storybench.org/mapping-search-data-from-google-trends-in-r/)
2)  [Using R to Analyze Fargo Crime Data](https://technistema.com/posts/using-r-to-analyze-fargo-crime-data/)

### Organizations

1)  [Global Investigative Journalism Network Data Journalism](https://gijn.org/data-journalism/)
2)  [ProPublica Data Institute 2018](https://github.com/propublica/data-institute-2018)
3)  [ProPublica Data Institute 2019](https://github.com/propublica/data-institute-2019)
4)  [SIGMA Awards](https://sigmaawards.org/projects/)
5)  [Knight Foundation: Misinformation](https://knightfoundation.org/features/misinfo/)
6)  [The Bureau of Investigative Journalism](https://www.thebureauinvestigates.com/)
7)  [Fake News Public Data Lab](https://fakenews.publicdatalab.org/)
8)  [AP DataKit](http://datakit.ap.org/)
9)  [Data Journalism Grants](https://pulitzercenter.org/grants-fellowships/opportunities-journalists/data-journalism-grants)
10) [A community conference for data makers everywhere](https://csvconf.com/)
11) [Google News Initiative](https://newsinitiative.withgoogle.com/resources/journalism/data-journalism/)

## Data Stories (Longform and In-depth articles)

### Story aggregators

1)  [Global Investigative Journalism Network Top 10](https://gijn.org/2022/07/29/data-journalism-top-10-kids-fashion-stereotypes-economic-sandwich-index-immigration-profits-and-florence-nightingales-graphics/)
2)  [Media Hack Collective](https://mediahack.co.za/)
3)  [12 brilliant data journalism projects of 2021](https://datajournalism.com/read/blog/best-data-journalism-projects-2021)
4)  [Data Journalism: Some Favorite Examples](https://datajournalism.com/read/handbook/one/introduction/some-favorite-examples)
5)  [Examples of Award-winning Data Journalism](https://sites.lib.uh.edu/datajournalism/overview/examples-of-award-winning-data-journalism/)
6)  [12 Best Data Journalism Examples:Storytelling with data](https://nocodewebscraping.com/data-journalism-examples/)
7)  [10 data journalism projects that made an impact in 2020: our ultimate COVID-19 roundup](https://datajournalism.com/read/longreads/covid-19-data-journalism)

### Top Data Story Examples

1)  [10 years. 180 school shootings. 356 victims.](https://edition.cnn.com/interactive/2019/07/us/ten-years-of-school-shootings-trnd/)
2)  [Blind Drunk](https://nmindepth.com/2022/blind-drunk/)
3)  [Uber Game](https://ig.ft.com/uber-game/)
4)  [What Africa will look like in 100 years](https://s.telegraph.co.uk/graphics/projects/Africa-in-100-years/)
5)  [ONE NATION, TRACKED](https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html)
6)  [Life in the camps](http://fingfx.thomsonreuters.com/gfx/rngs/MYANMAR-ROHINGYA/010051VB46G/index.html)
7)  [Life in Hong Kong's shoebox housing](https://multimedia.scmp.com/infographics/news/hong-kong/article/3180601/subdivided-flats/index.html)
8)  [The Airbnb effect](https://www.sfchronicle.com/airbnb-impact-san-francisco-2015/)
9)  [NSA Files Decoded](https://www.theguardian.com/world/interactive/2013/nov/01/snowden-nsa-files-surveillance-revelations-decoded#section/1)
10) [The Deadliest Jobs in America](https://www.bloomberg.com/graphics/2015-dangerous-jobs/)
11) [Congressional Tweets](https://congress.pudding.cool/)
12) [The Kim Foxx Effect](https://pudding.cool/2019/10/prosecutors/)
13) [What makes a titletown?](https://pudding.cool/2018/11/titletowns/)
14) [High street crisis deepens](https://www.theguardian.com/cities/ng-interactive/2019/jan/30/high-street-crisis-town-centres-lose-8-of-shops-in-five-years)
15) [The use of political ads on facebook in the run-up to the European Parliament elections 2019 in Austria](https://rpubs.com/zoowalk/FB_EP2019/)
16) [What the Democratic Presidential Candidates Care About, in 44,000 Tweets](https://www.bloomberg.com/graphics/2020-democratic-presidential-candidate-policies/)
17) [How many high school stars make it in the NBA?](https://pudding.cool/2019/03/hype/)
18) [The Facebook Scandal](https://www.liip.ch/en/blog/the-facebook-scandal-or-how-to-predict-psychological-traits-from-facebook-likes)
