---
title: "Data Visualization (General)"
toc: true
---

On this page, you will find a list of general data visualization resources. First, there is a list of data visualization specialists and companies to follow. Additionally, there are practical introductions to data visualization, style guidelines, and books.

## Data Visualization (Blogs)

A listing of data visualization specialists and companies to follow:

### People

1)  [Maarten Lambrechts](https://www.maartenlambrechts.com/)
2)  [Ada Homolova](http://homolova.sk/)
3)  [Lisa Charlotte Muth](https://lisacharlottemuth.com/)
4)  [Zev Ross](http://www.zevross.com/)
5)  [Edward Tufte](https://www.edwardtufte.com/tufte/)
6)  [CÉDRIC SCHERER](https://www.cedricscherer.com/top/links/)
7)  [Kieran Healy](https://kieranhealy.org/)
8)  [Little Miss Data](https://www.littlemissdata.com/)
9)  [Julie Peasley](https://www.juliepeasley.com/)

### Companies and Tools

1)  [SPJ Toolbox](https://www.journaliststoolbox.org/2023/05/25/online_journalism/)
2)  [Washington Post Tools](https://www.storybench.org/35-data-visualization-tools-that-the-washington-post-uses/)
3)  [Stamen](https://stamen.com/)
4)  [StatSilk](https://www.statsilk.com/)
5)  [Infogram](https://infogram.com/)
6)  [PiktoChart](https://piktochart.com/)
7)  [Genially](https://genially.com/)

## Data Visualization (General)

### Portfolios

1) [PerThirtySix](https://perthirtysix.com/)


### Selecting the appropriate chart types

1)  [Visual Vocabulary](http://ft-interactive.github.io/visual-vocabulary/)
2)  [The unspoken rules of visualisation](https://datajournalism.com/read/longreads/the-unspoken-rules-of-visualisation)
3)  [What Are Data Visualization Style Guidelines?](https://medium.com/nightingale/style-guidelines-92ebe166addc)
4)  [Data visualization](https://m2.material.io/design/communication/data-visualization.html)
5)  [Why scientists need to be better at data visualization](https://knowablemagazine.org/article/mind/2019/science-data-visualization)
6)  [Data Viz Project](https://datavizproject.com/)
7)  [A Tufte Handout Example](https://rstudio.github.io/tufte/)
8)  [A periodic table of visualization methods](https://www.visual-literacy.org/periodic_table/periodic_table.html)
9)  [Data Viz Design](https://ericwagner10.notion.site/Data-Viz-Design-fe78e46eb48d44cdb70a3c19b42bbfce)
10) [Dataviz guidelines: starting with why](https://figuresandfigures.substack.com/p/dataviz-guidelines-starting-with)
11) [Flourish Best Practices](https://flourish.studio/blog/dataviz-best-practice/)
12) [Stephen Few Notes](https://www.perceptualedge.com/article-index.php)
13) [11 Learnings From 11 Charts](https://3mw.albert-rapp.de/p/3mw-11-learnings-11-charts)

### Selecting the appropriate colors

1)  [Color in Data Vis](https://blog.datawrapper.de/category/color-in-data-vis/)
2)  [Color Brewer](https://colorbrewer2.org/)
3)  [Your Friendly Guide to Colors in Data Visualisation](https://blog.datawrapper.de/colorguide/)
4)  [Who can use this color combination?](https://www.whocanuse.com/)

### Data Viz Challenges

1)  [Black in Data Vis Challenge](https://www.datavisualizationsociety.org/black-in-data-challenge)
2)  [VIZRISK CHALLENGE STEPS](https://understandrisk.org/vizrisk/steps/#part1)
3)  [NMLM DataViz Challenge](https://www.nnlm.gov/nec/resources/datavizchallenge)

### Books

1)  [A Reader on Data Visualization](https://mschermann.github.io/data_viz_reader/)
2)  [Data Visualization: A practical introduction](https://socviz.co/)
