---
title: "Data Visualization (R)"
toc: true
---

This page contains a list of resources focused on data visualization in R. There are links to books, templates, tutorials, and courses. Additionally, for those interested in using coding for art, there is a section on \"Data aRtistry.\"

## Curated Links by other data viz specialists

1)  [Awesome ggplot2](https://github.com/erikgahner/awesome-ggplot2)

## Books

1)  [An introduction to data visualization protocols for wet lab scientists](https://joachimgoedhart.github.io/DataViz-protocols/)
2)  [Cookbook for R](http://www.cookbook-r.com/Graphs/)
3)  [R Graphics Cookbook](https://r-graphics.org/)
4)  [Data Visualization with R](https://rkabacoff.github.io/datavis/)
5)  [Data visualisation using R, for researchers who don't use R](https://psyteachr.github.io/introdataviz/index.html)
6)  [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)
7)  [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/index.html)
8)  [R4DS Data Visualization](https://r4ds.had.co.nz/data-visualisation.html)
9)  [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/)
10) [BBC Visual and Data Journalism cookbook for R graphics](https://bbc.github.io/rcookbook/)
11) [ggplot2](https://thisisdaryn.github.io/gcubed/ggplot.html)

## Templates

1)  [R CHARTS](https://r-charts.com/)
2)  [The R Graph Gallery](https://r-graph-gallery.com/index.html)
3)  [ggplot2 extensions](https://exts.ggplot2.tidyverse.org/gallery/)
4)  [A Scientist's Guide to R: Step 3.1 - data visualization with ggplot2+](https://craig.rbind.io/post/2021-05-17-asgr-3-1-data-visualization/)
5)  [ggplot tricks](https://github.com/teunbrand/ggplot_tricks)
6)  [Designing ggplots](https://designing-ggplots.netlify.app/#1)
7)  [BBC Style Plot Templates](https://github.com/bbc/bbplot)
8)  [a ggplot2 grammar guide](https://evamaerey.github.io/ggplot2_grammar_guide/about)
9)  [Tom's Cookbook for Better Viz](https://jthomasmock.github.io/nfl_plotting_cookbook/)
10) [12 ggplot extensions for snazzier R graphics](https://www.infoworld.com/article/3667496/12-ggplot-extensions-for-snazzier-r-graphics.html)
11) [Data Visualization Packages for R you should check out in 2022](https://citedrive.medium.com/data-visualization-packages-for-r-you-should-check-out-in-2022-35f3b56425ff)

## Courses

1)  [Graphic Design with ggplot2](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/)
2)  [Data Visualization in R](https://www.datavis.ca/courses/RGraphics/)
3)  [Data Visualization](https://datavizm20.classes.andrewheiss.com/)
4)  [SDS 375: Data Visualization in R](https://wilkelab.org/SDS375/)

## Tutorials and Notes

### Basics

1)  [Top 50 ggplot2 Visualizations - The Master List (With Full R Code)](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
2)  [The Complete ggplot2 Tutorial - Part1 \| Introduction To ggplot2 (Full R code)](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html)
3)  [Best ggplot visualizations](https://nextjournal.com/jk/best-ggplot)
4)  [A quick introduction to ggplot2](https://towardsdatascience.com/a-quick-introduction-to-ggplot2-d406f83bb9c9)
5)  [Getting started with data visualization in R using ggplot2](https://www.storybench.org/getting-started-data-visualization-r-using-ggplot2/)
6)  [The Evolution of a ggplot (Ep. 1)](https://cedricscherer.netlify.app/2019/05/17/the-evolution-of-a-ggplot-ep.-1/)
7)  [A ggplot2 Tutorial for Beautiful Plotting in R](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/)
8)  [R you ready to make charts?](https://www.williamrchase.com/slides/ggplot_intro.html#1)
9)  [The ggplot flibbook](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1)
10) [Getting started with data visualization in R using ggplot2](https://www.storybench.org/getting-started-data-visualization-r-using-ggplot2/)
11) [ggplot2: Mastering the basics](https://www.rebeccabarter.com/blog/2017-11-17-ggplot2_tutorial/)
12) [Graphing with ggplot](https://www.miriamheiss.com/posts/graphing-with-ggplot/)
13) [10 Levels of ggplot2: From Basic to Beautiful](https://medium.com/compassred-data-blog/10-levels-of-ggplot2-from-basic-to-beautiful-5ce3c4e7624f)
14) [Practical ggplot2](https://wilkelab.org/practicalgg/)
15) [Beautiful plotting in R: A ggplot2 cheatsheet](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/)
16) [The Good, the Bad and the Ugly: how (not) to visualize data](https://shirinsplayground.netlify.app/2020/10/goodbadugly/)
17) [Six things I always Google when using ggplot2](https://ivelasq.rbind.io/blog/things-i-google/)
18) [ggplot2tutor](https://ggplot2tutor.com/)

### Troubleshooting

1)  [Common R Mistakes in Data Viz](https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html)

### Enhancing Plots (with Labels, Axes, Themes, Scales, and Other Options)

1)  [Quick and easy ways to deal with long labels in ggplot2](https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/)
2)  [Making text labels the same size as axis labels in ggplot2](https://wjschne.github.io/posts/making-text-labels-the-same-size-as-axis-labels-in-ggplot2/)
3)  [Labelling area plots](https://bjnnowak.netlify.app/2021/08/10/r-labelling-area-plots/)
4)  [Level Up Your Labels: Tips and Tricks for Annotating Plots](https://www.cararthompson.com/talks/user2022/)
5)  [Increase & Decrease Number of Axis Ticks in R (2 Examples)](https://statisticsglobe.com/increase-decrease-number-axis-ticks-r)
6)  [ggplot2 Theme Elements Demonstration](https://henrywang.nl/ggplot2-theme-elements-demonstration/)
7)  [How to use multiple colour scales in ggplot with {ggnewscale}](https://gradientdescending.com/how-to-use-multiple-color-scales-in-ggplot-with-ggnewscale/)
8)  [Spruce up your ggplot2 visualizations with formatted text](https://www.slideshare.net/ClausWilke/spruce-up-your-ggplot2-visualizations-with-formatted-text)
9)  [Themes to Improve Your ggplot figures](https://rfortherestofus.com/2019/08/themes-to-improve-your-ggplot-figures/)
10) [How to Add Labels Directly in ggplot2](https://datavizpyr.com/direct-labeling-with-secondary-axis-trick-ggplot2-r/)
11) [Generate your own ggplot theme gallery](https://martinctc.github.io/blog/vignette-generate-your-own-ggplot-theme-gallery/)
12) [ggpattern](https://evamaerey.github.io/flipbooks/ggpattern/ggpattern#1)
13) [{ggtext} for images as x-axis labels](https://jcarroll.com.au/2019/08/13/ggtext-for-images-as-x-axis-labels/)
14) [GGPLOT THEMES GALLERY](https://www.datanovia.com/en/blog/ggplot-themes-gallery/)
15) [ggplot theme tester](https://github.com/martinctc/ggplot_theme_tester)
16) [Introducing 'optout' - A package for optimizing graphics output](https://coolbutuseless.github.io/2020/04/03/introducing-optout-a-package-for-optimizing-graphics-output/)
17) [ggcute](https://github.com/sharlagelfand/ggcute)
18) [Radial Patterns in ggplot2](https://ijeamaka-anyene.netlify.app/posts/2021-01-04-radial-patterns-in-ggplot2/)
19) [Reordering and facetting for ggplot2](https://juliasilge.com/blog/reorder-within/)
20) [Accelerate your plots with ggforce](https://rviews.rstudio.com/2019/09/19/intro-to-ggforce/)
21) [ggrapid](https://konradsemsch.netlify.app/2019/08/2019-08-29-ggrapid-create-neat-and-complete-ggplot-visualizations-with-as-little-code-as-possible/)
22) [Patchwork R package goes nerd viral](https://www.littlemissdata.com/blog/patchwork)
23) [ggthemes](https://github.com/jrnold/ggthemes)
24) [htmlwidgets](http://gallery.htmlwidgets.org/)
25) [ggchicklet](https://rud.is/b/2019/09/14/september-2019-democratic-debates-added-to-ggchicklet/)
26) [ggplot date helpers](https://scottishsnow.wordpress.com/2020/04/24/lubridate-ggplot-date-helpers/)
27) [12 Extensions to ggplot2 for More Powerful R Visualizations](https://mode.com/blog/r-ggplot-extension-packages/)
28) [Improving a Visualization](https://jcarroll.com.au/2021/07/02/improving-a-visualization/)
29) [ggplot theme for publication ready Plots](https://github.com/koundy/ggplot_theme_Publication)
30) [WHY NOT DO THAT WITH R?](http://rich-iannone.github.io/DiagrammeR/)

### Various graph types

1)  [Creating flowcharts with {ggplot2}](https://nrennie.rbind.io/blog/2022-06-06-creating-flowcharts-with-ggplot2/)
2)  [Dendrograms in R, a lightweight approach](https://atrebas.github.io/post/2019-06-08-lightweight-dendrograms/)
3)  [Racing Barchart with gganimate](https://evamaerey.github.io/little_flipbooks_library/racing_bars/racing_barcharts.html#1)
4)  [Racing Barplots with {ggpattern}, {flagon} & {gganimate}](https://coolbutuseless.github.io/2020/04/12/racing-barplots-with-ggpattern-flagon-gganimate/)
5)  [R base plotting without wrappers](http://karolis.koncevicius.lt/posts/r_base_plotting_without_wrappers/)
6)  [How to basic: bar plots](https://www.brodrigues.co/blog/2020-04-12-basic_ggplot2/)
7)  [Network Visualizations in R](https://mr.schochastics.net/material/netVizR/)
8)  [Great Looking Tables](https://posit.co/blog/great-looking-tables-gt-0-2/)
9)  [ggplot2 Bar Chart](https://www.programmingwithr.com/ggplot2-bar-chart-simple-to-powerful-themes-with-kaggle-notebook/)
10) [How to build Animated Charts like Hans Rosling --- doing it all in R](https://towardsdatascience.com/how-to-build-animated-charts-like-hans-rosling-doing-it-all-in-r-570efc6ba382)
11) [How to create Bar Race Animation Charts in R](https://www.programmingwithr.com/how-to-create-animated-bar-race-charts-in-r/)
12) [Animating Your Data Visualizations Like a Boss Using R](https://towardsdatascience.com/animating-your-data-visualizations-like-a-boss-using-r-f94ae20843e3)
13) [barbarplots](https://barbarplots.github.io/)
14) [Dynamic display of data with animated plots](https://thenode.biologists.com/dynamic-display-of-data-with-animated-plots/research/)
15) [Beginners Cookbook for Interactive Visualization in R with highcharter](https://www.programmingwithr.com/how-to-create-animated-bar-race-charts-in-r/)

### Data Viz Examples

1)  [Can I do that? Inspiration from a Pudding data visualization](https://austinwehrwein.com/data-visualization/winningest/)
2)  [Visualizing the heterogeneity of single cell data from time-lapse imaging](https://thenode.biologists.com/visualizing-heterogeneity-of-imaging-data/research/)
3)  [the seven living generations in America](https://www.jtimm.net/posts/seven-generations/)
4)  [this old house](https://www.jtimm.net/posts/this-old-house/)
5)  [Visualizing real house price plots](http://lenkiefer.com/2022/05/30/2022-05-30-real-hpi-plots/)
6)  [State Unemployment Claims](https://rviews.rstudio.com/2020/04/16/state-unemployment-claims/)
7)  [A look into U.S. infectious diseases](https://austinwehrwein.com/data-visualization/diseases/)
8)  [NYT-style urban heat island maps](https://www.katiejolly.io/blog/2019-08-28/nyt-urban-heat)
9)  [Ryo Viz Data Viz Gallery](https://ryo-n7.github.io/visualizations/)
10) [Reproducing an Axios plot](https://rud.is/b/2019/12/27/short-attention-span-theatre-reproducing-axios-1-big-thing-google-trends-2019-news-in-review-with-ggplot2/)
11) [Create a Visual CV](http://adomingues.github.io/2020/11/25/visual-cv/)
12) [Visualize monthly precipitation anomalies](https://dominicroye.github.io/en/2019/visualize-monthly-precipitation-anomalies/)
13) [Inspiration from Flowing Data](https://austinwehrwein.com/data-visualization/salaries/)
14) [Visualizing Time Series](https://tsggplot.netlify.app/#1)
15) [Visualising high-dimensional data](https://github.com/dicook/useR2019_highd_vis)
16) [Data Storytelling in R](https://posit.co/blog/how-i-use-stories-to-share-data-at-meetings/)
17) [William Chase - Data Viz Projects](https://www.williamrchase.com/projects)

## Data aRtistry

1)  [Getting started in #rtistry](https://ivelasq.rbind.io/blog/rtistry-intro/)
2)  [ART FROM CODE](https://art-from-code.netlify.app/)
3)  [Life Through A Mathematician's Eyes](https://lifethroughamathematicianseyes.wordpress.com/2014/11/13/parametric-equations/)
4)  [aRt](https://github.com/nrennie/aRt)
5)  [Rtistry Gallery](https://thetidytrekker.com/rtistry.html)
6)  [Art by Claus O. Wilke](https://clauswilke.com/art/post/)
7)  [Unpredictable paintings](https://blog.djnavarro.net/posts/2021-11-01_unpredictable-paintings/)
8)  [Mystery curves](https://georgemsavva.github.io/creativecoding/posts/mystery/)
9)  [Flow Fields](https://tylerxhobbs.com/essays/2020/flow-fields)
10) [HOW TO WORK WITH FLOW FIELDS IN R](https://jiwanheo.rbind.io/post/2021-09-17-how-to-work-with-flow-fields-in-r/)
