---
title: "Biomechanics and Sports Engineering"
toc: true
---

The Biomechanics and Sports Engineering page provides a curated collection of resources. Included here is a list of books, tutorials, and personal blogs and websites.

## Biomechanics

### Curated collection of resources

1)  [A curated repository of biomechanical resources](https://github.com/modenaxe/awesome-biomechanics)

### Personal Blogs and Websites

1)  [Stuart McErlain-Naylor Biomechanics Website](https://www.stuartmcnaylor.com/)

### Labs

### Books

1)  [Biomechanics of Movement](https://biomech.stanford.edu/)
2)  [The Biomechanics of Solids and Fluids: The Physics of Life](http://hobbieroth.blogspot.com/2016/09/the-biomechanics-of-solids-and-fluids.html)

### Tutorials and Lectures

1)  [Biomechanics of Movement Classroom](https://simtk-confluence-homeworks.stanford.edu:8443/display/BMH/Lectures)
2)  [Reinbolt Research Group](http://rrg.utk.edu/resources/BME599/lectures.html)
3)  [Notes on Scientific Computing for Biomechanics and Motor Control](https://github.com/BMClab/BMC)
4)  [Understanding Biomechanics and Body Movement](https://www.verywellfit.com/understanding-biomechanics-3498389)
5)  [The Biomechanist](https://www.biomechanist.net/)

### Sports Engineering and Movement Science

1)  [Becoming a Sports Engineer](https://engineeringsport.co.uk/becoming-a-sports-engineer/)
2)  [Peak Performance Project](https://www.p3.md/)
3)  [BTS Bioengineering](https://www.btsbioengineering.com/)
4)  [Sparta Science](https://spartascience.com/)
