---
title: "Biomedical Image Analysis and Microscopy"
toc: true
---

## E-Books and Tutorials

1)  [Bio-image Analysis Notebooks](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/intro.html)
2)  [Python BioImage Analysis Tutorial](https://github.com/WhoIsJack/python-bioimage-analysis-tutorial)
3)  [BIAPy: BioImage Analysis with Python](https://github.com/guiwitz/BIAPy)
4)  [Analyzing fluorescence microscopy images with ImageJ](https://petebankhead.gitbooks.io/imagej-intro/content/)
5)  [NEUBIAS Academy](http://eubias.org/NEUBIAS/training-schools/neubias-academy-home/)
6)  [Grand Challenge: ML in Biomedical Imaging](https://grand-challenge.org/)
7)  [Carpenter Lab Public Slides](https://drive.google.com/drive/folders/1AEDQcWq68WyWlgV_34KhkNAxSDFkFyh8)
8)  [Lecture - Applied Bioimage Analysis (2020)](https://git.mpi-cbg.de/rhaase/lecture_applied_bioimage_analysis_2020)
9)  [Deep learning in microscopy collection](https://www.nature.com/collections/cfcdjceech)
10) [Awesome Cytodata](https://github.com/cytodata/awesome-cytodata)
11) [CellProfiler Practical: Counting of in situ PLA signals per cell](https://github.com/tischi/cellprofiler-practical-NeuBIAS-Lisbon-2017/blob/master/practical-handout.md)
12) [SciPy 2021 Bioimage Analysis Fundamentals in Python](https://github.com/sofroniewn/tutorial-scipy2021-bioimage-analysis-fundamentals)
13) [Several image processing workflow examples](https://cif.unil.ch/cif-wiki/several-image-processing-workflow-examples/)
14) [Recommended Readings and Viewings](https://cif.unil.ch/external-resources/#Image_Processing)
15) [BioImage Model Zoo](https://bioimage.io/#/)
16) [deepImageJ](https://deepimagej.github.io/)
17) [Bristol: Image analysis courses](http://www.bristol.ac.uk/wolfson-bioimaging/equipment/image-analysis/image-analysis-courses/)
18) [Bioconductor: Basics of image data and spatial patterns analysis in R](https://www.bioconductor.org/help/course-materials/2015/BioC2015/BioC2015Oles.html#1)
19) [EASY IMAGE PROCESSING IN R USING THE MAGICK PACKAGE](https://www.datanovia.com/en/blog/easy-image-processing-in-r-using-the-magick-package/)
20) [Bio-Image analysis with Python and Napari - DIGS-BB Light Microscopy Course 2022](https://biapol.github.io/DIGS-BB_LM_Course_Bio-Image_Analysis_2022/intro.html)
21) [First Principles of Computer Vision](https://fpcv.cs.columbia.edu/Monographs)
22) [Data Science in Cell Imaging](https://assafzar.wixsite.com/dsci2020/lecture-slides)
23) [The OpenAI Microscope](https://microscope.openai.com/models)
24) [The Journal of Machine Learning for Biomedical Imaging](https://www.melba-journal.org/)
25) [CELL TRACKING CHALLENGE](http://celltrackingchallenge.net/)
26) [Bioimage Analysis Course: The Life Cycle of an Image Data Set](https://www.ibiology.org/online-biology-courses/bioimage-analysis-course/)
27) [Statistics for Neuroscientists: Image Analysis](https://stats4neuro.netlify.app/)
28) [Image Segmentation with Python](https://www.kite.com/blog/python/image-segmentation-tutorial/)

## BioImaging Software

1)  [A Hitchhiker's guide through the bio-image analysis software universe](https://febs.onlinelibrary.wiley.com/doi/full/10.1002/1873-3468.14451)
2)  [ImageScience Software](https://imagescience.org/software/)
3)  [DeepLabCut](https://github.com/DeepLabCut/DeepLabCut-Workshop-Materials/blob/master/DLCcourse.md)
4)  [DeepLabCut GUI](https://deeplabcut.github.io/DeepLabCut/docs/PROJECT_GUI.html)
5)  [Discover, install, and share napari plugins](https://www.napari-hub.org/)
6)  [napari](https://napari.org/stable/)
7)  [Chan Zuckerberg napari](https://chanzuckerberg.github.io/napari-plugin-alfa-cohort/projects/)
8)  [StarDist - Object Detection with Star-convex Shapes](https://github.com/stardist/stardist)
9)  [cellfinder-napari](https://github.com/brainglobe/cellfinder-napari)
10) [ilastik](https://www.ilastik.org/)
11) [YAPiC: Yet Another Pixel Classifier (based on deep learning)](https://yapic.github.io/yapic/)
12) [CellPose](https://www.cellpose.org/)
13) [CellProfiler tutorials](https://github.com/CellProfiler/tutorials)
14) [Piximi App](https://www.piximi.app/)
15) [Piximi GitHuc](https://github.com/piximi)
16) [Icy](https://icy.bioimageanalysis.org/)
17) [nucleAIzer](http://www.nucleaizer.org/)
18) [ScientiFig](https://github.com/baigouy/ScientiFig)
19) [uList](https://www.microlist.org/explore/?type=tools&sort=a-z)
20) [ImJoy](https://imjoy.io/)
21) [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic)

## Microscopy

1)  [The OpenFlexure Project](https://openflexure.org/)
2)  [NanoJ-Fluidics: open-source fluid exchange in microscopy](https://github.com/HenriquesLab/NanoJ-Fluidics/wiki)
3)  [Microscopy Series](https://www.ibiology.org/online-biology-courses/microscopy-series/)
4)  [The Power Of Observation](https://www.gene.com/stories/the-power-of-observation)
5)  [Royal Microscopy Society](https://www.rms.org.uk/events/imaging-oneworld-series.html)
