---
title: "General Teaching Resources"
toc: true
---

The general teaching resources page provides resources focused on teaching STEM subjects, as well as links to teaching aids for more efficient teaching.

## Teaching STEM Subjects

### A curated collection of resources

1)  [Teaching Tech Together](http://teachtogether.tech/en/index.html)
2)  [Maintaining a laboratory notebook](https://colinpurrington.com/tips/lab-notebooks/)
3)  [Subjects and Skills for Graduate Students in the Biological Sciences](https://wilkelab.org/classes/BIO384C_fall_2015.html)
4)  [Scientific Figure Design](https://www.bioinformatics.babraham.ac.uk/training.html#figuredesign)
5)  [The Mediocre Programmer](https://themediocreprogrammer.com/build/html/the_mediocre_programmer.html)
6)  [Teach Yourself Programming in Ten Years](https://norvig.com/21-days.html)
7)  [Spurious Correlations and Associated Papers](https://tylervigen.com/)
8)  [Wonder Tools Teaching Toolkit](https://wonder.craft.me/4PTeHobSdhjxlO)
9)  [Wonder Tools Blog by Jeremy Caplan](https://wondertools.substack.com/)
10) [Making Annotated Presentations](https://simonwillison.net/2023/Aug/6/annotated-presentations/)
11) [OTTR - GitHub sites and courses for busy people](https://www.ottrproject.org/)
12) [Loqui: A Shiny app for Creating Automated Videos](https://loqui.fredhutch.org/)


### Preventing Cognitive Overload

1) [Reducing Cognitive Overload While Teaching](https://hbsp.harvard.edu/inspiring-minds/reducing-cognitive-overload-while-teaching)
2) [Give Your Brain a Break—Course Design Tips to Avoid Feeling Overwhelmed](https://hbsp.harvard.edu/inspiring-minds/course-design-tips-to-avoid-feeling-overwhelmed)
3) [A programmer's cognitive load](https://stitcher.io/blog/a-programmers-cognitive-load)
4) [How do you use the redundancy principle to avoid cognitive overload?](https://www.linkedin.com/advice/3/how-do-you-use-redundancy-principle-avoid)
5) [Designing Project-Based Learning to Decrease Cognitive Load](https://spencerauthor.com/pbl-cognitive-load/)
6) [Cognitive Load Theory And Instructional Design](https://elearningindustry.com/cognitive-load-theory-and-instructional-design)
7) [11 Science-Backed Ways to Prevent Cognitive Overload in eLearning](https://www.learnworlds.com/prevent-cognitive-overload-in-elearning/)

## Teaching Aids

### Typing Test

1)  [Keyboard Test](https://www.keybr.com/)
2)  [Typing Test](https://10fastfingers.com/typing-test/english)

### Simulations

1)  [Physics Education and Training Simulations](https://phet.colorado.edu/en/simulations/browse)
2)  [Circuit simulation and schematics](https://www.circuitlab.com/)
3)  [Interactive STEM activities](https://learn.concord.org/)
4)  [GeoGebra for Teaching and Learning Math](https://www.geogebra.org/)
5)  [GeoGebra Simulations](https://www.geogebra.org/m/nk83G3WY)

### Online Textbooks

1)  [Free and flexible textbooks and resources](https://openstax.org/)
2)  [College Physics](https://openstax.org/details/books/college-physics)

### Design and Illustrations

1)  [One Page Website](https://carrd.co/)
2)  [Illustrations](https://blush.design/)
3)  [BioRender Learning Hub](https://learn.biorender.com/)
4)  [Beautiful Free Stock Video Footage](https://coverr.co/)

### Miscellaneous Tools

1)  [Whiteboard](https://witeboard.com/268a6870-cc8e-11ec-b94c-e3c8f550f39e)
2)  [Etherpad](https://etherpad.org/)
3)  [Active Memory](https://miku.github.io/activememory/)
4)  [Scientific Place](https://scientific.place/)
5)  [Sounds of Colleagues](https://soundofcolleagues.com/#)
6) 
