---
title: "RStudio and Carpentries Certification"
toc: true
---

This page provides a list of tutorials, resources and study notes for RStudio and Carpentries certification.

## RStudio Certification

### Tutorials and Resources

1)  [R4DS Book -- Prep for Exam](https://sciencificity.github.io/R4DS_study_exams/index.html)
2)  [POSIT/R Training Videos](https://posit.co/resources/videos/)
3)  [POSIT Primers](https://posit.cloud/learn/primers)
4)  [RStudio Sample Exams](https://education.rstudio.com/blog/2020/08/more-example-exams/)
5)  [Miscellaneous Teaching Notes 1](https://docs.google.com/document/d/17mDR_Tup5aSA_Qc2HZaFB8TloGDDUnjxnD4bPWdkseA/edit)
6)  [Miscellaneous Teaching Notes 2](https://docs.google.com/document/d/1uEWz_dMtky2Zjrq8CMFL7Zls-55Ig8KrrdVGwSiw3PI/edit)
7)  [RStudio Instructor Training](https://drive.google.com/drive/folders/13ohFt3D0EJ5PDbMaWTxnHH-hwA7G0IvY)

### Study notes from RStudio Certified Trainers

1)  [Laurie L Baker RStudio Instructor Training](https://github.com/LaurieLBaker/r-studio-instructor-training)
2)  [Marly Comar Gotti Tidyverse Certification](https://marlycormar.github.io/tidyverse_sample_exam/sample_exam_sols/sols.html)
3)  [Yuqi Liao: Getting Certified as an RStudio Instructor](https://www.yuqiliao.com/blog/rstudiocertification/)
4)  [Shel Kariuki: The RStudio Certification Process](https://shelkariuki.netlify.app/blog/certification/)
5)  [Florencia D'Andrea: Two examples of iteration with purrr - Class for the RStudio certification](https://florencia.netlify.app/blog/two-examples-of-iteration-with-purrr.en-us/)
6)  [Silvia Canelon RStudio Certification](https://silviacanelon.com/blog/2020-rstudio-instructor-certification-tidyverse/)
7)  [Silvia Canelon RStudio Certification Training 1](https://spcanelon.github.io/rit-tidyverse-exam/14-strings/index.html#1)
8)  [Silvia Canelon RStudio Certification Training 2](https://spcanelon.github.io/rit-tidyverse-exam/21-iteration/index.html#1)
9)  [Silvia Canelon R4DS Certification Training 1](https://r4ds.github.io/bookclub-R_for_Data_Science/Presentations/Week04/Cohort1/Chapter5Slides.html#1)
10) [Paloma Rojas Saunero RStudio Certification Training 1](https://palolili23.github.io/texam/teaching_exam.html)
11) [Paloma Rojas Saunero RStudio Certification Exam Slides](https://palolili23.github.io/texam/slides.html#1)
12) [Paloma Rojas Saunero RStudio Certification Exam Notes](https://palolili23.github.io/texam/tidyr.html)

## Carpentries Certification

1)  [The Carpentries](https://carpentries.org/)
2)  [Data Carpentry](https://datacarpentry.org/lessons/)
3)  [Software Carpentry](https://software-carpentry.org/lessons/)
4)  [Library Carpentry](https://librarycarpentry.org/lessons/)
