---
title: "Public Datasets"
toc: true
---

This page provides a comprehensive collection of resources on datasets that can be used for statistical analysis, machine learning, and data journalism. The page includes curated collections of free and open data sources, industry-specific data, and multiple public data sources.

## Working with Data

1)  [Data Literacy](https://dataliteracy.com/)
2)  [Using Data Appropriately](https://data.org/guides-resources/)
3)  [Sharing Data](https://posit.co/blog/how-i-use-stories-to-share-data-at-meetings/)
4)  [WTF CSV Data Organization](https://databasic.io/en/wtfcsv/)
5)  [Data Cleaning](https://cghlewis.com/categories/tutorials/)

## Free and Open Data

1)  [Open Africa Data](https://africaopendata.org/)
2)  [Data Africa](https://dataafrica.io/)
3)  [Our World in Data](https://ourworldindata.org/)
4)  [California Data Sources](https://hillcrestadvisory.com/2019/01/20/california-data-sources/)
5)  [DataSF](https://datasf.org/opendata/)
6)  [NYC Open Data](https://opendata.cityofnewyork.us/)
7)  [The Humanitarian Data Exchange](https://data.humdata.org/)
8)  [Global Data Barometer](https://globaldatabarometer.org/)
9)  [Microsoft Research Open Data](https://msropendata.com/)
10) [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)
11) [Multiple Public Data Sources](https://docs.google.com/document/d/1Ads4XsCjXmDrdGRgfmm_OgRdpFcl6Qhs6SOllNGyq7Y/edit)
12) [Data Science Central Datasets](https://www.datasciencecentral.com/a-plethora-of-data-set-repositories/)
13) [70 Amazing Free Data Sources You Should Know](https://www.kdnuggets.com/2017/12/big-data-free-sources.html)
14) [Rebecca Barter - List of Public Data Repositories](https://www.rebeccabarter.com/blog/2023-03-28-data_sources.html)
15) [GapMinder](https://www.gapminder.org/)

## Afro-Specific Data

1) [Black Wealth Data Center](https://blackwealthdata.org/)
2) [Africa Data Hub](https://www.africadatahub.org/)
3) [Black Demographics](https://blackdemographics.com/)
4) [New Population Counts for 62 Detailed Black or African American Groups](https://www.census.gov/library/stories/2023/10/2020-census-dhc-a-black-population.html)
5) [African American Studies at Princeton](https://libguides.princeton.edu/c.php?g=84056&p=542224)
6) [HBCU Rankings](https://www.usnews.com/best-colleges/rankings/hbcu)
7) [HBCU Stats](https://nces.ed.gov/FastFacts/display.asp?id=667)
8) [Origin Source of Black Immigrants](https://www.pewresearch.org/2022/01/20/the-caribbean-is-the-largest-origin-source-of-black-immigrants-but-fastest-growth-is-among-african-immigrants/)
9) [About 6 million U.S. adults identify as Afro-Latino](https://www.pewresearch.org/short-reads/2022/05/02/about-6-million-u-s-adults-identify-as-afro-latino/)
10) [Obesity in the African-American Community](https://www.apa.org/pi/oema/resources/ethnicity-health/african-american/obesity)
11) [The economic state of Black America: What is and what could be](https://www.mckinsey.com/featured-insights/diversity-and-inclusion/the-economic-state-of-black-america-what-is-and-what-could-be)
12) [Cancer statistics for African American/Black People 2022](https://acsjournals.onlinelibrary.wiley.com/doi/10.3322/caac.21718)
13) [Resident population of the United States by race from 2000 to 2022](https://www.statista.com/statistics/183489/population-of-the-us-by-ethnicity-since-2000/)
14) [Health of Black or African American non-Hispanic Population](https://www.cdc.gov/nchs/fastats/black-health.htm)
15) [Black/African American Health](https://minorityhealth.hhs.gov/blackafrican-american-health)
16) [HIV on Racial and Ethnic Minorities in the U.S.](https://www.hiv.gov/hiv-basics/overview/data-and-trends/impact-on-racial-and-ethnic-minorities)

## Machine Learning Training Data

1)  [Datasets for Machine Learning and Deep Learning](https://sebastianraschka.com/blog/2021/ml-dl-datasets.html)
2)  [Best Public Datasets for Machine Learning and Data Science](https://pub.towardsai.net/best-datasets-for-machine-learning-data-science-computer-vision-nlp-ai-c9541058cf4f)
3)  [Machine Learning Food Datasets Collection](https://hackernoon.com/machine-learning-food-datasets-collection-fz5i130w0)
4)  [Datasets for Data Science and Machine Learning](https://elitedatascience.com/datasets)
5)  [R Datasets](https://vincentarelbundock.github.io/Rdatasets/articles/data.html)
6)  [Kaggle Datasets](https://www.kaggle.com/datasets)
7)  [Google Research Datasets](https://datasetsearch.research.google.com/)

## Industry-Specific Data

1)  [NHS R-community Datasets](https://nhs-r-community.github.io/NHSRdatasets/)
2)  [Infectious Diseases Data Observatory](https://www.iddo.org/)
3)  [Inside Airbnb](http://insideairbnb.com/get-the-data/)
4)  [School Shootings USA](https://github.com/cnnlabs/cnn-school-shooting-data/)
5)  [Political Datasets](https://github.com/erikgahner/PolData)
6)  [Eighty-Five Points Sports Data](http://eightyfivepoints.blogspot.com/p/reading-list.html)
7)  [Poverty and Inequality Platform API](https://blogs.worldbank.org/opendata/how-use-pips-api)
8)  [Nasdaq Data Link](https://data.nasdaq.com/)
9)  [Analyze Survey Data for Free](http://asdfree.com/)
10) [Global Clinical Research Data](https://vivli.org/)
11) [Google Community Mobility Reports](https://www.google.com/covid19/mobility/)
12) [15 Open Datasets for Healthcare](https://odsc.medium.com/15-open-datasets-for-healthcare-830b19980d9)
13) [Demographic and Health Surveys](https://dhsprogram.com/data/available-datasets.cfm)
14) [FiveThirtyEight Data](https://data.fivethirtyeight.com/)
15) [StatsBomb Open Data](https://github.com/statsbomb/open-data)
16) [NCD Risk Factor Datasets](https://ncdrisc.org/index.html)
17) [Food Systems Dashboard](https://www.foodsystemsdashboard.org/)
18) [Global Energy Monitor](https://globalenergymonitor.org/)
