---
title: "Sports Data Science"
toc: true
---

This page provides a comprehensive collection of resources on sports data science. The page includes links to tutorials, datasets, journal articles, and personal blogs focused on sports data science.

## Sports Data Science Blogs

### Multiple Sports

1)  [Sweep Sports Analytics](https://sweepsportsanalytics.com/)
2)  [Jason Zivkovic](https://www.dontblamethedata.com/)
3)  [SPORT DATA SCIENCE](https://theparttimeanalyst.com/)

### Soccer

1)  [SBNation Blogs](https://www.sbnation.com/blogs?_gl=1*k529md*)
2)  [Sports Intelligence](https://www.twentyfirstgroup.com/)
3)  [11tegen11](https://11tegen11.com/)
4)  [Karun Singh](https://karun.in/)
5)  [Mackay Analytics](https://mackayanalytics.nl/)
6)  [Son of a Corner](https://www.sonofacorner.com/)
7)  [Saints by Numbers](https://szfh.github.io/)
8)  [Achim Zeileis](https://www.zeileis.org/)
9)  [Opta Analyst](https://theanalyst.com/eu)
10) [The Come on Man](https://thecomeonman.github.io/)
11) [The Last Man Analytics](https://thelastmananalytics.home.blog/)
12) [Analytics FC](https://analyticsfc.co.uk/)
13) [Brendan Kent](https://www.brendankent.com/blog)
14) [WyScout](https://footballdata.wyscout.com/)
15) [Biscuit Chaser FC](https://biscuitchaserfc.blogspot.com/)
16) [StatsBomb](https://statsbomb.com/what-we-do/hub/)
17) [EightyFivePoints](https://eightyfivepoints.blogspot.com/)
18) [Owen Thompson](https://otstats.github.io/)
19) [Tony El Habr](https://tonyelhabr.rbind.io/index.html)
20) [11v11](https://www.11v11.com/)

### Basketball Analytics

1)  [Dribble analytics](https://dribbleanalytics.blog/)

## Sports Data Science Stories

1)  [Armando Broja: A Case Study](https://jackelderton.com/2022/07/11/armando-broja-a-case-study/)
2)  [Out of the Park](https://fiftytwo.in/paradigm-shift/out-of-the-park/)
3)  [How Data (and Some Breathtaking Soccer) Brought Liverpool to the Cusp of Glory](https://www.nytimes.com/2019/05/22/magazine/soccer-data-liverpool.html)
4)  [How data analysis helps football clubs make better signings](https://www.ft.com/content/84aa8b5e-c1a9-11e8-84cd-9e601db069b8)
5)  [LOAN PATHWAYS: THE ACADEMY MODEL](https://analyticsfc.co.uk/blog/2021/08/02/loan-pathways-the-academy-model/)
6)  [LOAN PATHWAYS: THE PORTFOLIO MODEL](https://analyticsfc.co.uk/blog/2021/08/16/loan-pathways-the-portfolio-model/)
7)  [LOAN PATHWAYS: THE MULTI-CLUB MODEL](https://analyticsfc.co.uk/blog/2021/08/31/loan-pathways-the-multi-club-model/)

## Sports Data Science Journals and Readings

1)  [EightyFivePoints Reading List & Data](http://eightyfivepoints.blogspot.com/p/reading-list.html)
2)  [Sports analytics reading list](https://www.brendankent.com/blog/sports-analytics-reading-list)
3)  [Sports analytics conference video archives](https://www.brendankent.com/blog/where-to-watch-sports-analytics-conference-video-archives)
4)  [Journal of Sports Analytics](https://journalofsportsanalytics.com/)
5)  [Journal of Quantitative Analysis in Sports](https://www.degruyter.com/journal/key/jqas/html)

## Tools and Databases

### Multiple Sports

1)  [PySport](https://opensource.pysport.org/)
2)  [DTAI SPORTS ANALYTICS LAB](https://dtai.cs.kuleuven.be/sports/)
3)  [SportsDataVerse](https://sportsdataverse.org/)
4)  [Sports guideR](https://docs.google.com/spreadsheets/d/16Xvhl7fCKEs1JTr-VXPZDmctO2gq4TcmuNmAhoHQQs0/edit#gid=1034341673)
5)  [Sports Reference](https://www.sports-reference.com/)
6)  [SFU Sports Analytics Group Virtual Seminar](http://www.sfu.ca/sportsanalytics/Seminars.html)
7)  [Brescia BDAS Lab](https://bodai.unibs.it/bdsports/#block-1)
8)  [SPORT PERFORMANCE ANALYSIS](https://www.sportperformanceanalysis.com/)
9)  [Bruin Sports Analytics](https://www.bruinsportsanalytics.com/)
10) [Spotrac](https://www.spotrac.com/)
11) [THE GREAT ANALYTICS RANKINGS](http://www.espn.com/espn/feature/story/_/id/12331388/the-great-analytics-rankings)
12) [Sport Informatics and Analytics](https://wikieducator.org/Sport_Informatics_and_Analytics/Pattern_Recognition/Using_R#cite_note-45)

### Soccer

#### Curated list of soccer resources

1)  [Awesome Soccer Analytics](https://github.com/matiasmascioto/awesome-soccer-analytics)
2)  [Edd Webster Football Analytics](https://github.com/eddwebster/football_analytics)
3)  [Soccer Analytics Handbook](https://github.com/devinpleuler/analytics-handbook/)

#### Individual resources

1)  [Soccermatics](https://soccermatics.readthedocs.io/en/latest/)
2)  [MPL Soccer](https://mplsoccer.readthedocs.io/en/latest/index.html)
3)  [American Soccer Analysis](https://www.americansocceranalysis.com/)
4)  [Total Football Analysis](https://totalfootballanalysis.com/)
5)  [Learn Python & Data Science With Football](https://fcpython.com/)
6)  [Learn R & Data Science With Football](http://www.fcrstats.com/)
7)  [Experimental 361](https://experimental361.com/)
8)  [Barca Innovation Hub](https://barcainnovationhub.com/)
9)  [Training Ground Guru](https://trainingground.guru/)
10) [SportSciData](https://sportscidata.com/)
11) [FourFourTwo](https://www.fourfourtwo.com/)
12) [Twelve Football](https://twelve.football/premierleague)
13) [Football Science](https://www.footballscience.net/)
14) [THE DATA CRUNCHING FOOTBALL EXPERT](https://analytics.twelve.football/analytics)
15) [worldfootballR](https://jaseziv.github.io/worldfootballR/index.html)
16) [Languages and tools to learn for sports analytics](https://www.brendankent.com/blog/languages-and-tools-to-learn-for-sports-analytics)
17) [Coding for sports analytics](https://www.brendankent.com/blog/coding-for-sports-analytics-resources-to-get-started)

#### Databases

1)  [CIES Football Observatory](https://football-observatory.com/)
2)  [The Fjelstul English Football Database](https://github.com/jfjelstul/englishfootball)
3)  [The Fjelstul World Cup Database](https://github.com/jfjelstul/worldcup)
4)  [StatsBomb Open Data](https://github.com/statsbomb/open-data)
5)  [Football Data UK](https://www.football-data.co.uk/data.php)
6)  [SoFIFA](https://sofifa.com/)

#### American Football

1)  [Big Data Bowl '21 Submission](https://midsprint.io/portfolio/index.html)
2)  [Modeling Player Biomechanics](https://www.kaggle.com/code/haljordan/modeling-player-biomechanics/notebook)
3)  [Fantasy Football Analytics](https://fantasyfootballanalytics.net/)

#### Basketball

1)  [NBAstuffer](https://www.nbastuffer.com/)

### Tutorials

#### Soccer

1)  [A Beginner's Introduction to Mixed Effects Models in Sport](https://meghan.rbind.io/blog/2022-06-28-a-beginner-s-guide-to-mixed-effects-models/)
2)  [How Our Club Soccer Predictions Work](https://fivethirtyeight.com/methodology/how-our-club-soccer-predictions-work/)
3)  [Google Research Football with Manchester City F.C.](https://www.kaggle.com/c/google-football)
4)  [Data in Elite Sport](https://jacquietran.github.io/2019_may_rladies_akl/R/#1)
5)  [COMPUTER VISION IN SPORT](https://www.sportperformanceanalysis.com/article/computer-vision-in-sport)
6)  [Getting Started with Free StatsBomb Event Data](https://thelastmananalytics.home.blog/2019/06/16/15-getting-started-with-free-statsbomb-event-data-xg-shot-map-tutorial/)
7)  [Predicting Football Results With Statistical Modelling](https://dashee87.github.io/data%20science/football/r/predicting-football-results-with-statistical-modelling/)
8)  [Liverpool 20-21 EPL Performance](https://rodserr.github.io/logbook/posts/2021-05-31-liverpool-20-21-epl-performance/?panelset=diogo-jota)
9)  [Explaining Expected Threat](https://soccermatics.medium.com/explaining-expected-threat-cbc775d97935)
10) [Working with data in elite sport](https://jacquietran.github.io/2019_may_rladies_akl/R/#1)
11) [Mathematical Modelling of Football](https://henrikwarne.com/2020/11/25/mathematical-modelling-of-football/)
12) [10 Steps to Get Started in Sports Analytics](https://www.r-bloggers.com/2021/08/10-steps-to-get-started-in-sports-analytics/)
13) [Flank Attacks Visualisation](https://npranav10.github.io/blog/entries-into-final-third.html)
14) [Doing More With StatsBomb Data in R](https://statsbomb.com/articles/soccer/doing-more-with-statsbomb-data-in-r/)
15) [How sports scientists can use ggplot2 in R to make better visualisations](https://www.mitchhenderson.org/2020/04/how-sports-scientists-can-use-ggplot2-in-r-to-make-better-visualisations/)
16) [Visualizing the Premier League](https://ryo-n7.github.io/2019-11-21-visualize-EPL-part-1/)
17) [Fitting your own football xG model](https://www.datofutbol.cl/xg-model/)
18) [PassSonar](https://github.com/etmckinley/PassSonar)
19) [Adding Football Crests to Scatter Plots in R](https://dm13450.github.io/2021/02/01/PointsToImages.html)

#### Basketball

1)  [How to make NBA shots charts in R](https://www.owenlhjphillips.com/new-blog/2020/6/25/how-to-make-nba-shots-charts-in-r)
2)  [Animating NBA Play by Play using R](http://curleylab.psych.columbia.edu/nba.html)
