---
title: "Social Media and Music Analysis"
toc: true
---

On this page, there is a comprehensive collection of resources focused on social media and music analysis. The page includes links to books, courses, and tutorials that can help with social media, music, and lyric analysis.

## Social Media Analysis

### Books

1)  [Text Mining with R](https://www.tidytextmining.com/index.html)
2)  [Social Media Mining](http://www.socialmediamining.info/)
3)  [Social Media Mining (Slides)](http://www.socialmediamining.info/slides/)

### Tutorials

1)  [ANALYSING TWITTER DATA WITH R](https://marionlouveaux.fr/blog/twitter-analysis-part1/#go-to-folding-div)
2)  [ANALYSING TWITTER DATA: EXPLORING USER PROFILES AND RELATIONSHIPS](https://marionlouveaux.fr/blog/twitter-analysis-part2/)
3)  [ANALYSING TWITTER DATA: EXPLORING TWEETS CONTENT](https://marionlouveaux.fr/blog/2020-04-18_analysing-twitter-data-with-r-part3/)
4)  [4 ways how to create a gradient word cloud in R](https://datacornering.com/4-ways-how-to-create-a-gradient-word-cloud-in-r/)
5)  [Analyzing Google Trends with R: Retrieve and plot with gtrendsR](https://www.datacareer.ch/blog/analyzing-google-trends-with-r-retrieve-and-plot-with-gtrendsr/)
6)  [Quantitative Analysis of Political Text](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/quantitative-analysis-of-political-text/)
7)  [Classifying Tweets for Sentiment Analysis](https://medium.com/vickdata/detecting-hate-speech-in-tweets-natural-language-processing-in-python-for-beginners-4e591952223)
8)  [Advancing Text Mining with R and quanteda](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/advancing-text-mining/)
9)  [Using Twitter With Python And Tweepy](https://www.blog.pythonlibrary.org/2019/08/06/using-twitter-with-python-and-tweepy/)
10) [USING R TO ANALYZE AND VISUALIZE TWEETS FROM SACNAS](https://www.raynamharris.com/blog/sacnas_rtweet/)
11) [Twitter "Account Analysis" in R](https://rud.is/b/2019/09/14/twitter-account-analysis-in-r/)
12) [Calculating (Twitter) Vocabulary Breadth of U.S. Presidential Candidates Using TTR](https://gilliganondata.github.io/twitter-ttr/twitter-ttr-refined.nb.html)
13) [Twitter data analysis in R](https://poissonisfish.com/2019/10/09/twitter-data-analysis-in-r/)
14) [Twitter's Feelings About Programming Languages](https://www.garrickadenbuie.com/blog/tweet-poll-programming-languages/)
15) [Look who's tweeting: 2020 Presidential Candidates](https://austinwehrwein.com/data-visualization/2020candidates/)
16) [A TidyText Analysis With R](https://methodmatters.github.io/country-vs-rb-hiphop-lyrics-part-2-tidytext/)
17) [Using Twitter as a data source an overview of social media research tools (2021)](https://blogs.lse.ac.uk/impactofsocialsciences/2021/05/18/using-twitter-as-a-data-source-an-overview-of-social-media-research-tools-2021/)

### Courses

1)  [Text As Data](https://joeornstein.github.io/text-as-data/)

### Projects

1)  [twitter-sentiment-analysis](https://github.com/topics/twitter-sentiment-analysis)
2)  [Analytics Master's Research Project](https://rstudio-pubs-static.s3.amazonaws.com/389843_5be8625c9e784095b0770529c47e8af1.html)

## Music and Lyric Analysis

### Basics

1)  [Spotify R&D](https://research.atspotify.com/)
2)  [spotifyr package](https://github.com/charlie86/spotifyr)
3)  [13 best websites to analyze your Spotify data](https://mashable.com/article/best-websites-to-analyze-your-spotify-data)

### Tutorials

1)  [Spotify Songs: Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md)
2)  [How to integrate Spotify and Genius API to easily crawl song lyrics with Python](https://dev.to/willamesoares/how-to-integrate-spotify-and-genius-api-to-easily-crawl-song-lyrics-with-python-4o62)
3)  [Profiling Songs on Spotify Using Cluster Analysis](https://medium.com/analytics-vidhya/profiling-songs-on-spotify-using-cluster-analysis-185535598ebd)
4)  [Sentiment Analysis of Most Streamed Spotify Artists](http://rstudio-pubs-static.s3.amazonaws.com/494094_eb7a7e1d68854c17b47c7aeb36fe6738.html)
5)  [Lyric Analysis with NLP & Machine Learning with R](https://www.datacamp.com/tutorial/R-nlp-machine-learning)
6)  [What's popping?: An Exploratory Analytics Project on What Makes Popular Music Popular](https://towardsdatascience.com/whats-popping-an-exploratory-analytics-project-on-what-makes-popular-music-popular-7b183e6e48d2)
7)  [Analysis of my Spotify in R with spotifyr package](https://rpubs.com/womeimingzi11/how_my_spotify_looks_like)
8)  [Game of Thrones: Exploratory and Sentiment Analysis](https://medium.com/analytics-vidhya/game-of-thrones-exploratory-and-sentiment-analysis-75dd2f81ba1c)
9)  [tayloR](https://medium.com/@simranvatsa5/taylor-f656e2a09cc3)
10) [Exploring the Spotify API with R](https://msmith7161.github.io/what-is-speechiness/)
11) [Learn tidytext with my new learnr course](https://juliasilge.com/blog/learn-tidytext-learnr/)
12) [Text mining with tidy data principles](https://juliasilge.shinyapps.io/learntidytext/#section-introduction)
13) [Are Pop Lyrics Getting More Repetitive?](https://pudding.cool/2017/05/song-repetition/)
14) [Spotify Songs: An analysis of the spotify dataset](https://rstudio-pubs-static.s3.amazonaws.com/594440_b5a14885d559413ab6e57087eddd68e6.html)
15) [FitteR HappieR](https://www.rcharlie.com/blog/fitter-happier/)
16) [Data Wrangling - Spotify Dataset Analysis](https://rpubs.com/nairrj/data-wrangling-on-spotify-data)
17) [Understanding + classifying genres using Spotify audio features](https://www.kaylinpavlik.com/classifying-songs-genres/)
18) [What Makes a Hit](https://www8.gsb.columbia.edu/articles/projects/what-makes-a-hit/)
19) [What Makes Songs Popular? It's All About 'You'](https://knowledge.wharton.upenn.edu/article/what-makes-songs-popular-its-all-about-you/)
20) [Can big data really predict what makes a song popular?](https://theconversation.com/can-big-data-really-predict-what-makes-a-song-popular-189052)
21) [PCA and the #TidyTuesday best hip hop songs ever](https://juliasilge.com/blog/best-hip-hop/)
22) [Blue Christmas: A data-driven search for the most depressing Christmas song](https://www.caitlinhudon.com/posts/2017/12/22/blue-christmas)
23) [Using Data to Find the Angriest Death Grips Song](https://medium.com/@evanopp/angriest-death-grips-data-anger-502168c1c2f0)
24) [Spotify songs popularity analysis](https://www.kaggle.com/code/fpolcari/spotify-songs-popularity-analysis)
25) [Nigerian Songs Spotify EDA](https://www.kaggle.com/code/moremaaz/nigerian-songs-spotify-eda/notebook)
26) [Sentiment Analysis of Spotify, Amazon Music, and Pandora user reviews](https://rpubs.com/michelledo202/sa)
