---
title: "Agriculture and Farming Stories"
toc: true
---

## Agriculture

### Digital Agriculture and New Technologies

1)  [Digital Agriculture](https://www.usaid.gov/digitalag)
2)  [Crop Yield Increase With Precision Technologies](https://eos.com/blog/crop-yield-increase/)
3)  [Connecterra](https://www.connecterra.io/)
4)  [The Precision Farming Magazine](https://www.agleader.com/insights-magazine/)
5)  [Harvest Robotics](https://www.harvestcroorobotics.com/)
6)  [IoT Farming Solutions 1](https://upande.com/)
7)  [IoT Farming Solutions 2](https://arinifu.com/)
8)  [Garage Hydroponics](http://www.garagehydroponics.com/)
9)  [Next-generation harvesting robots](https://www.tevel-tech.com/)
10) [Hydroponics Africa](https://www.hydroponicsafrica.org/)
11) [Passion Fruit and Tech](https://blog.bluelab.com/scotts-place-pro-controller-case-study)
12) [Cultured Meat](https://rethinkpriorities.org/publications/cultured-meat-a-comparison-of-techno-economic-analyses)
13) [Modern Ag Canada](https://modernagriculture.ca/emagazine/)
14) [ProteINSECT](https://www.proteinsect.eu/)
15) [Build a Solar Cooker and Dryer](https://www.builditsolar.com/Projects/Cooking/cooking.htm)

### Agricultural Resources

1)  [Feed the Future Innovation Lab for Horticulture](https://horticulture.ucdavis.edu/)
2)  [Latia Resource Center](https://latiaresourcecenter.org/)
3)  [Sustainable Food Lab](https://sustainablefoodlab.org/)
4)  [PostHarvest](https://postharvest.ucdavis.edu/)
5)  [Rural Solutions Portal](https://ruralsolutionsportal.org/en/solutions)
6)  [Africa Value Chain Dev](https://avcdkenya.net/)
7)  [African indigenous vegetables](https://horticulture.ucdavis.edu/crop/african-indigenous-vegetables)
8)  [Increased Photosynthesis](https://ripe.illinois.edu/)

### Model Farms

1)  [Aero Farms](https://www.aerofarms.com/)
2)  [Goat Farm](https://redwoodhill.com/)
3)  [Sundrop Farms](https://www.sundropfarms.com/)
4)  [RivenDale](https://rivendalefarms.com/)
5)  [Sicilian Passion](https://sicilian-passion.com/)

## Farming Stories (Longform and In-depth articles about farming around the world)

1)  [THIS TINY COUNTRY FEEDS THE WORLD](https://www.nationalgeographic.com/magazine/article/holland-agriculture-sustainable-farming)
2)  [The small Dutch town that wants to shape the future of your food](https://www.theguardian.com/world/2020/mar/05/how-a-small-dutch-town-is-shaping-the-future-of-your-food-wageningen-netherlands)
3)  [A Land Without Farmers](https://www.thejakartapost.com/longform/2020/08/13/a-land-without-farmers-indonesias-agricultural-conundrum.html)
4)  [Rio Fish](https://medium.com/@groundbreakers/rio-fish-creating-economic-opportunities-through-aquaculture-da5bff23b6)
