---
title: "Recommended Readings (General)"
toc: true
---

This page contains a list of readings that I would recommend for anyone. It includes articles with topics that range from religion, mental health, classic books and short stories.

## Interesting Articles and Speeches

1)  How Will You Measure Your Life? Clayton Christensen (2010)
2)  A World Split Apart. Alexander Solzhenitsyn (1978)
3)  The Inner Ring. CS Lewis (1944)

## My Favorite Short Stories

1)  How Much Land Does a Man Require? Leo Tolstoy (1886)
2)  The Americanization of Kambili. Tochi Eze (2022) [Link](https://catapult.co/stories/tochi-eze-fiction-short-story-the-americanization-of-kambili)
3)  The Street Sweep. Meron Hadero (2018) [Link](http://www.caineprize.com/new-page)

## Classics

1)  Night (Elie Wiesel)
2)  Gilead (Marilynne Robinson)

## Mental Health / Counseling / Peace of Mind

1)  When People Are Big and God Is Small: Overcoming Peer Pressure, Codependency, and the Fear of Man (Edward T. Welch)
2)  Seeing with New Eyes: Counseling and the Human Condition Through the Lens of Scripture (David A. Powlison)
3)  Man's Search for Meaning (Viktor E. Frankl)
4)  Absence of Mind: The Dispelling of Inwardness from the Modern Myth of the Self (Marilynne Robinson)

## Religious

1)  The Reason for God: Belief in an Age of Skepticism (Timothy J. Keller)
2)  The Cost of Discipleship (Dietrich Bonhoeffer)
3)  A Treatise of Earthly-Mindedness (Jeremiah Burroughs)
4)  The Knowledge of the Holy (A.W. Tozer)
5)  The Pursuit of God: The Human Thirst for the Divine (A.W. Tozer)
6)  A Bunch of Everlastings; Or, Texts That Made History (F.W. Boreham)
7)  A Packet of Surprises: The Best Essays and Sermons of F. W. Boreham (F.W. Boreham)
8)  The Screwtape Letters (C.S. Lewis)
9)  The Last Sin Eater (Francine Rivers)
10) Mere Christianity (C.S. Lewis)
